### ISSUE TITLE
Users shouldn't be forced to put config in root

### ISSUE THREAD

**Issue by ammaraskar** [mbax/SQLBansWeb#2]
Config files are generally tethered to the actual web files. I tested this script 

``` php
<?php

  function getDirectoryList ($directory)
  {

    // create an array to hold directory list
    $results = array();

    // create a handler for the directory
    $handler = opendir($directory);

    // open directory and walk through the filenames
    while ($file = readdir($handler)) {

      // if file isn't this directory or its parent, add it to the

      if ($file != "." && $file != "..") {
        $results[] = $file;
      }

    }

    // tidy up: close the handler
    closedir($handler);

    // done!
    return $results;

  }
  var_dump(getDirectoryList("/"));
?>
```

and this was the result:

```

array(13) {
  [0]=>
  string(11) "checkvirtfs"
  [1]=>
  string(3) "usr"
  [2]=>
  string(4) "home"
  [3]=>
  string(3) "lib"
  [4]=>
  string(3) "etc"
  [5]=>
  string(3) "bin"
  [6]=>
  string(3) "dev"
  [7]=>
  string(5) "lib64"
  [8]=>
  string(4) "proc"
  [9]=>
  string(3) "var"
  [10]=>
  string(3) "tmp"
  [11]=>
  string(4) "sbin"
  [12]=>
  string(3) "opt"
}
```

Correct me if I'm wrong but this would mean that the user would have to put the config file in the root of the server which is one of the silliest requirements I have ever seen, I recommend moving the config file to the assets folder.

**Comment by mbax** [comment]
Not everyone chroots, nor is it necessary for good security or even possible on some systems.  So yeah, drop the / requirement :P

**Comment by AgentK20** [comment]
Yeah, that was not actually supposed to be there. I believe it was originally "../../config.php" from FishFish0001, and that didn't work so tips dropped it to "/config.php". I noticed it a few days ago and thought "Oh.....fish wrote this and he probably knows more about it than me so I guess it works." Apparently not. Mbax has pushed a fix.
