### ISSUE TITLE
Don't use php's mysql extension

### ISSUE THREAD

**Issue by ammaraskar** [mbax/SQLBansWeb#3]
PHP's MySQL extension is no longer being maintained, even the documentation says not to use it for new code (http://www.php.net/manual/en/intro.mysql.php)

Please look to either using mysqli or pdo.
Lovely comparison: https://net.tutsplus.com/tutorials/php/pdo-vs-mysqli-which-should-you-use/

**Comment by AgentK20** [comment]
For the moment, I'm focusing on adding functionality, then making it look pretty and use the latest code. If you'd like to PR changes, I'll accept them, but it's low on my priority list ATM.

**Comment by mbax** [comment]
Lowwww priority.

(Hi!)
